# Minimal configuration to run PHP_CodeSniffer
# Can be replaced with SilverStripe-provided configuration if we need to run tests

language: php

php:
  - 7.4

install:
  - composer install

script:
  - vendor/bin/phpcs

cache:
  directories:
    - $HOME/.composer/cache/files
